name: elite_ambassadors
description: App Elite Ambassadors (MVP)
publish_to: "none"

version: 0.0.1+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.3.0
  cupertino_icons: ^1.0.6

firebase_core: ^2.27.0
firebase_auth: ^4.17.8
cloud_firestore: ^4.15.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
    
