name: elite_ambassadors
description: App Elite Ambassadors (MVP)
publish_to: "none"

version: 0.0.1+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # FlutterFire
  firebase_core: ^2.31.1
  firebase_auth: ^4.20.0
  cloud_firestore: ^4.17.5
  cloud_functions: ^4.5.6   # callable functions (paquete correcto)
  url_launcher: ^6.3.2
  
  # Routing
  go_router: ^14.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
